source 'https://rubygems.org'

ruby '2.6.3'

gem 'capybara'
gem 'celluloid-io'
gem 'cpf_cnpj'
gem 'credit_card_validations'
gem 'cucumber'
gem 'faker'
gem 'httparty'
gem 'pry'
gem 'pry-byebug'
gem 'rspec'
gem 'rubocop'
gem 'selenium-webdriver'
gem 'regexp_parser'
gem 'mime-types'
gem 'webdrivers'
gem 'report_builder'
